# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'ta9hJCqSerg8IOJ1jGZfnHPBA'
  twitter_api_secret: 'QgOiLl5OidMMdLEASWI6ObcFderSse4je4cm4r99xskAE14Gmj'

development:
  secret_key_base: c3a5957870042fbb2c72c20e84f207fbe0b39640042533520c5baa41f988b27ff7e6ab453f7cdb2d7d38ea7edff6304f0d9dee7352afb1bc2133a815ff5bfef6
  <<: *default_twitter

test:
  secret_key_base: 32e899a726b7280483b3ba0ffabe9690d656d30a40747b91b75f409ba42383d0946bb902ae887b31ab4157f5f3596a915e7ffba1905a0681201efef3bb2fa877
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
